theme: jekyll-theme-midnight
permalink: pretty
lang: en
timezone: Europe/Amsterdam
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: default
      permalink: /pages/:basename/
# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Volatco - Powerful Multicompute # the main title
tagline: The future of multiprogramming # it will display as the subtitle
description: >- # used by seo meta and the atom feed
  The most advanced computer in the world today.
url: "https://volatco.github.io"
pageviews:
  provider: # now only supports 'goatcounter'
theme_mode: dark
cdn: "https://volatco.tech"
avatar: "/images/volatco.jpg"
