theme: jekyll-theme-midnight
lang: en
timezone: Europe/Amsterdam
# jekyll-seo-tag settings â€º https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: A Powerful Multicomputer # the main title
tagline: The future of multicomputing # it will display as the subtitle
description: >- # used by seo meta and the atom feed
  Advanced multicomputing tech.
url: "https://volatco.github.io"
pageviews:
  provider: # now only supports 'goatcounter'
theme_mode: dark
cdn: "https://volatco.tech"
avatar: "/images/volatco.jpg"